import RoleAuthenticationCheckUser from "@/components/rolecheck/RoleAuthenticationCheckUser";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <RoleAuthenticationCheckUser/>
      <h1> This is the custom layouts for all the user routes</h1>
      {children}
    </>
  );
}
