import RoleAuthenticationCheckTrainer from "@/components/rolecheck/RoleAuthenticationCheckTrainer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <RoleAuthenticationCheckTrainer />
      <h1> This is the custome layouts for all the trainer routes</h1>
      {children}
    </>
  );
}
