import AdminLayout from "@/components/layouts/AdminLayout";
import RoleAuthenticationCheckAdmin from "@/components/rolecheck/RoleAuthenticationCheckAdmin";
import HomePageLogout from "@/components/usersidecomponents/HomePageLogout";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) { 
  return (
    <> 
    <RoleAuthenticationCheckAdmin/>
      <AdminLayout/>
      <HomePageLogout/>
      {children}
      <div>Footer</div>
    </>
  );
}
