import UserLayout from "@/components/layouts/UserLayout";
import RoleAuthenticationCheckUser from "@/components/rolecheck/RoleAuthenticationCheckUser";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <RoleAuthenticationCheckUser/> 
      <UserLayout/>
      {children}
    </>
  );
}
