import RoleAuthenticationCheckUser from "@/components/rolecheck/RoleAuthenticationCheckUser";
import {
  AlignJustify,
  Carrot,
  CircleUserRound,
  Dumbbell,
  Home,
  HomeIcon,
  IndianRupee,
  PersonStanding,
  UserCog,
} from "lucide-react";
import Link from "next/link";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import HomePageLogout from "@/components/usersidecomponents/HomePageLogout";
import {
  Sheet,
  SheetClose,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <RoleAuthenticationCheckUser />
      <div className="mt-6 max-w-8xl mx-auto px-4 sm:px-6 lg:px-8 h-screen">
        <nav className="flex justify-between items-center">
          <Link href="/user"><h1 className="text-2xl sm:text-3xl lg:text-4xl">Vigor</h1></Link>
          <ul className="hidden lg:flex justify-center items-center border-2 p-3 rounded-3xl bg-slate-500 gap-2">
            <li>
              <Link
                className="flex border-2 bg-slate-100 px-6 gap-1 border-none text-slate-800 rounded-3xl  p-2"
                href="/user"
              >
                <Home />
                Home
              </Link>
            </li>
            <li>
              <Link
                className="flex border-2 bg-slate-100 px-6 gap-1 border-none text-slate-800 rounded-3xl   p-2"
                href="/user/workout"
              >
                <Dumbbell />
                Workout
              </Link>
            </li>
            <li>
              <Link
                className="flex border-2 bg-slate-100 px-6 gap-1 border-none text-slate-800 rounded-3xl  p-2"
                href="/user/diet"
              >
                <Carrot />
                Diet
              </Link>
            </li>
            <li>
              <Link
                className="flex border-2 bg-slate-100 px-6 gap-1 border-none text-slate-800 rounded-3xl  p-2"
                href="/user/trainer"
              >
                <PersonStanding />
                Trainer
              </Link>
            </li>
            <li>
              <Link
                className="flex border-2 bg-slate-100 px-6 gap-1 border-none text-slate-800  rounded-3xl  p-2"
                href="/user/plan"
              >
                <IndianRupee />
                Plan
              </Link>
            </li>
          </ul>

          <div className="flex">
            <div >
            <HomePageLogout />
            </div>
            <div className="lg:hidden">
              <Sheet>
                <SheetTrigger>
                  <AlignJustify />
                </SheetTrigger>
                <SheetContent>
                  <SheetHeader>
                    <SheetTitle className="flex gap-2">
                      <CircleUserRound />
                      Hello, From Vigor
                    </SheetTitle>

                    <SheetDescription>Your account</SheetDescription>
                  </SheetHeader>
                  <div className="p-2 mt-6"></div>
                  <SheetClose asChild>
                    <div className="space-y-6 ml-7">
                      <a className="flex gap-2" href="/user/profile">
                        <UserCog color="#0006b8" />
                        Profile
                      </a>
                      <a className="flex gap-2" href="/user">
                        <HomeIcon />
                        Home
                      </a>
                      <a className="flex gap-2" href="/user/workout">
                        <Dumbbell />
                        Workout
                      </a>
                      <a className="flex gap-2" href="/user/diet">
                        <Carrot />
                        Diet
                      </a>
                      <a className="flex gap-2" href="/user/trainer">
                        <PersonStanding />
                        Trainer
                      </a>
                      <a className="flex gap-2" href="/user/plan">
                        <IndianRupee />
                        Plan
                      </a>
                    </div>
                  </SheetClose>
                </SheetContent>
              </Sheet>
            </div>
            <Avatar className="hidden lg:block">
              <Link href="/user/profile"><AvatarImage src="https://github.com/shadcn.png" /></Link>
              <AvatarFallback>CN</AvatarFallback>
            </Avatar>
          </div>
        </nav>
        {children}
        <div>Footer details</div>
      </div>
    </>
  );
}
